DELIMITER //
CREATE PROCEDURE FAKE_MUSTERI_KAYDI_OLUSTUR(IN MUSTERI_ADI VARCHAR(255))
 BEGIN
	DECLARE ARTIS INT;
    SET ARTIS = 0;
	WHILE ARTIS < 100 DO
	   INSERT INTO MUSTERI (ID, ADI, KAYIT_TARIHI) VALUES (ARTIS + 5, TO_STRING(ARTIS, MUSTERI_ADI), SUBDATE(CURDATE(), 7));
       SET ARTIS = ARTIS + 1;
       COMMIT;
	END WHILE;
 END //
DELIMITER ;



DELIMITER $$
 
create FUNCTION TO_STRING(SAYI1 INT, ADI VARCHAR(45) ) RETURNS VARCHAR(50)
    DETERMINISTIC
BEGIN
    DECLARE SONUC VARCHAR(50);
	SET SONUC = concat(SAYI1, " - ", ADI);
	RETURN (SONUC);
END;

DELIMITER $$
CREATE TRIGGER TR_MUSTERI_KAYIT_TARIHI_EKLE 
    BEFORE INSERT ON MUSTERI
    FOR EACH ROW 
BEGIN
	SET NEW.KAYIT_TARIHI = NOW();
END$$
DELIMITER ;


DELIMITER $$
CREATE TRIGGER TR_MUSTERI_KAYIT_TARIHI_EKLE 
    BEFORE INSERT ON MUSTERI
    FOR EACH ROW 
BEGIN
	SET NEW.KAYIT_TARIHI = (select MAX(KAYIT_TARIHI) FROM MUSTERI);
    IF NEW.KAYIT_TARIHI IS NULL THEN
		SET NEW.KAYIT_TARIHI = NOW();
	END IF;
END$$
DELIMITER ;